name: Matrix
on: push

jobs:
  node-version:
    strategy:
      # job will run 8 times
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: [6,8,10]
        exclude:
          - os: ubuntu-latest
            node_version: 6
        include:
          - os: ubuntu-latest
            node_version: 8
            is_unbunto_8: "true"
      #fail-fast: true  # run all even if one fails
      max-parallel: 2
    runs-on: ${{ matrix.os}}
    env:
      IS_UBUNTO_8: ${{ matrix.is_ubuntu_8 }}
    steps:
      - name: Log node version
        run: node -v
      - uses: actions/setup-node@v1
        with:
          #node-version: 6
          node-version: ${{ matrix.node_version }}
      - name: Log node version
        run: |
          node -v
          echo $IS_UBUNTU_8